
-<protNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00">


-<infProt>

<tpAmb>2</tpAmb>

<verAplic>SVRS202202091911</verAplic>

<chNFe>33220315698425000193550010000030301674945254</chNFe>

<dhRecbto>2022-03-09T20:05:24-03:00</dhRecbto>

<nProt>333220000099517</nProt>

<digVal>prV7RtFQ/yYG3sazlKsaQl8gv+Q=</digVal>

<cStat>100</cStat>

<xMotivo>Autorizado o uso da NF-e</xMotivo>

</infProt>

</protNFe>

</nfeProc>