11RO	Rondonia	    RO 
12AC	Acre 	        AC 
13AM 	Amazonas	    AM
14RR 	Roraima 	    RR 
15PA 	Para 	        PA 
16AP	Amapa 	        AP 
17TO 	Tocantins 	    TO 
21MA 	Maranhao 	    MA
22PI 	Piaui	        PI
23CE 	Ceara       	CE
24RN 	Rio G Norte     RN 
25PB 	Paraiba 	    PB 
26PE 	Pernambuco 	    PE 
27AL 	Alagoas 	    AL 
28SE	Sergipe	        SE
29BA	Bahia	        BA
31MG	Minas Gerais    MG
32ES	Espo Santo	    ES
33RJ	Rio de Janeiro	RJ
35SP	São Paulo	    SP
41PR	Paraná	        PR
42SC	Santa Catarina	SC
43RS	Rio Grde do Sul	RS
50MS	Mato Gro do Sul	MS
51MT	Mato Grosso  	MT
52GO	Goias	        GO
53DF	Distrito FederalDF