<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.portalfiscal.inf.br/nfeabi" targetNamespace="http://www.portalfiscal.inf.br/nfeabi" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema_v1.01.xsd"/>
	<xs:include schemaLocation="nfeabiTiposBasico_v1.00.xsd"/>
	<xs:simpleType name="TVerEvento">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[0-9]{1}\.[0-9]{2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TCSTIBSCBS">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TcClassTribIBSCBS">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[0-9]{6}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TtpEventoPagParcela">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:enumeration value="01"/>
			<xs:enumeration value="02"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TNome">
		<xs:restriction base="TString">
			<xs:minLength value="2"/>
			<xs:maxLength value="60"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TSeq1a99">
		<xs:restriction base="xs:string">
			<xs:whiteSpace value="preserve"/>
			<xs:pattern value="[1-9][0-9]?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="TGIBSCBSEventoPagParcela">
		<xs:sequence>
			<xs:element name="vOperacIndiv" type="TDec_1302" minOccurs="0"/>
			<xs:element name="vRedAjusteIndiv" type="TDec_1302" minOccurs="0"/>
			<xs:element name="vRedSocialIndiv" type="TDec_1302" minOccurs="0"/>
			<xs:element name="vBC" type="TDec_1302"/>
			<xs:element name="gIBSUF" type="TGIBSUF"/>
			<xs:element name="gIBSMun" type="TGIBSMun"/>
			<xs:element name="gCBS" type="TGCBS"/>
			<xs:element name="gTribCompraGov" type="TGTribCompraGov" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TAdquirApropCredInd">
		<xs:sequence>
			<xs:choice>
				<xs:element name="CNPJ" type="TCnpj"/>
				<xs:element name="CPF" type="TCpf"/>
			</xs:choice>
			<xs:element name="xNome" type="TNome"/>
			<xs:element name="pParticip" type="TDec_0304"/>
		</xs:sequence>
		<xs:attribute name="nAdquir" type="TSeq1a99" use="required"/>
	</xs:complexType>
	<xs:complexType name="TEvento">
		<xs:annotation>
			<xs:documentation>Tipo Evento da NF-e ABI</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="infEvento">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="cOrgao">
							<xs:annotation>
								<xs:documentation>Código do órgão de recepção do Evento, conforme Tabela do IBGE ou: 91=Ambiente Nacional. Informar o código da UF para este evento.</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{2}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="tpAmb">
							<xs:annotation>
								<xs:documentation>Identificação do Ambiente:
1=Produção
2=Homologação</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:enumeration value="1"/>
									<xs:enumeration value="2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:choice>
							<xs:element name="CNPJ" type="TCnpj">
								<xs:annotation>
									<xs:documentation>CNPJ do autor do evento</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="CPF" type="TCpf">
								<xs:annotation>
									<xs:documentation>CPF do autor do evento</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:choice>
						<xs:element name="chNFeABI">
							<xs:annotation>
								<xs:documentation>Chave de Acesso da NF-e ABI à qual o evento será vinculado</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{6}[A-Z0-9]{12}[0-9]{26}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="dhEvento">
							<xs:annotation>
								<xs:documentation>Data e hora do evento no formato AAAA-MM-DDThh:mm:ssTZD (UTC)</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="tpEvento">
							<xs:annotation>
								<xs:documentation>Código do evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{6}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nSeqEvento">
							<xs:annotation>
								<xs:documentation>Sequencial do evento para o mesmo tipo de evento. Informar o valor "1" para este evento.</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[1-9][0-9]{0,2}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="verEvento" type="TVerEvento">
							<xs:annotation>
								<xs:documentation>Versão do grupo de detalhe do evento</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="detEvento">
							<xs:annotation>
								<xs:documentation>Detalhes do evento. Inserir neste local o XML específico do tipo de evento.</xs:documentation>
							</xs:annotation>
							<xs:complexType>
								<xs:sequence>
									<xs:any processContents="skip">
										<xs:annotation>
											<xs:documentation>XML do evento específico (cancelamento, pagamento de parcela, apropriação de créditos individuais)</xs:documentation>
										</xs:annotation>
									</xs:any>
								</xs:sequence>
								<xs:attribute name="versaoEvento" type="TVerEvento" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="Id" use="required">
						<xs:annotation>
							<xs:documentation>Identificador da TAG a ser assinada, formado por "ID" + tpEvento + chNFeABI + nSeqEvento</xs:documentation>
						</xs:annotation>
						<xs:simpleType>
							<xs:restriction base="xs:ID">
								<xs:pattern value="ID[0-9]{12}[A-Z0-9]{12}[0-9]{26}[1-9][0-9]{0,2}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element ref="ds:Signature"/>
		</xs:sequence>
		<xs:attribute name="versao" type="TVerEvento" use="required"/>
	</xs:complexType>
	<xs:complexType name="TRetEvento">
		<xs:annotation>
			<xs:documentation>Tipo retorno do Evento da NF-e ABI</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="infEvento">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Id" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Identificador da TAG a ser assinada, somente deve ser informado se o órgão de registro assinar a resposta. Preencher com o número do protocolo precedido pela literal "ID"</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:ID">
									<xs:pattern value="ID[0-9]{17}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="tpAmb">
							<xs:annotation>
								<xs:documentation>Identificação do Ambiente:
1=Produção
2=Homologação</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:enumeration value="1"/>
									<xs:enumeration value="2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="verAplic">
							<xs:annotation>
								<xs:documentation>Versão da aplicação que registrou o Evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:minLength value="1"/>
									<xs:maxLength value="20"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="cOrgao">
							<xs:annotation>
								<xs:documentation>Código do órgão de recepção do Evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{2}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="cStat">
							<xs:annotation>
								<xs:documentation>Código do status da resposta</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{3}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="xMotivo">
							<xs:annotation>
								<xs:documentation>Descrição do status da resposta</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="TString">
									<xs:minLength value="1"/>
									<xs:maxLength value="255"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="chNFeABI" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Chave de Acesso da NF-e ABI vinculada ao evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{6}[A-Z0-9]{12}[0-9]{26}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="tpEvento" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Código do evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{6}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="xEvento" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Descrição do resultado do processamento do evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="TString">
									<xs:minLength value="5"/>
									<xs:maxLength value="60"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nSeqEvento" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Sequencial do evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[1-9][0-9]{0,2}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="dhRegEvento" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Data e hora de registro do evento no formato AAAA-MM-DDTHH:MM:SSTZD (UTC). Se o evento for rejeitado informar a data e hora de recebimento do evento.</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="nProt" minOccurs="0">
							<xs:annotation>
								<xs:documentation>Número do Protocolo do Evento</xs:documentation>
							</xs:annotation>
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:whiteSpace value="preserve"/>
									<xs:pattern value="[0-9]{15}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element ref="ds:Signature" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="versao" type="TVerEvento" use="required"/>
	</xs:complexType>
	<xs:complexType name="TProcEvento">
		<xs:annotation>
			<xs:documentation>Tipo Evento da NF-e ABI processado</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="eventoNFeABI" type="TEvento"/>
			<xs:element name="retEventoNFeABI" type="TRetEvento"/>
		</xs:sequence>
		<xs:attribute name="versao" type="TVerEvento" use="required"/>
		<xs:attribute name="ipTransmissor" use="optional">
			<xs:annotation>
				<xs:documentation>IP do transmissor do documento fiscal para o ambiente autorizador</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="nPortaCon" use="optional">
			<xs:annotation>
				<xs:documentation>Porta de origem utilizada na conexão (De 0 a 65535)</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[0-9]{1,5}"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="dhConexao" use="optional">
			<xs:annotation>
				<xs:documentation>Data e Hora da Conexão de Origem</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:whiteSpace value="preserve"/>
					<xs:pattern value="(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00))"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
</xs:schema>