[versao]
Data=20/09/2023

[BR]
NF-e=https://www.nfe.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=resumo&tipoConteudo=7PhJ+gAVw2g=
CT-e=https://www.cte.fazenda.gov.br/portal/consultaRecaptcha.aspx?tipoConsulta=resumo&tipoConteudo=cktLvUUKqh0=
NFC-e=
NFC-e(h)=
NFC-e_ConsultaManual=
NFC-e_ConsultaManual(h)=
NFS-e=https://www.producaorestrita.nfse.gov.br/ConsultaPublica?tpc=1&chave=#chave_acesso#
NFS-e(h)=https://www.producaorestrita.nfse.gov.br/ConsultaPublica?tpc=1&chave=#chave_acesso#

[AC]
NF-e=http://sefaznet.ac.gov.br/nfe/NFe.jsp?opc=1
CT-e=
NFC-e=http://www.sefaznet.ac.gov.br/nfce/qrcode
NFC-e(h)=http://www.hml.sefaznet.ac.gov.br/nfce/qrcode
NFC-e_ConsultaManual=www.sefaznet.ac.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaznet.ac.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[AL]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp
NFC-e(h)=http://nfce.sefaz.al.gov.br/QRCode/consultarNFCe.jsp
NFC-e_ConsultaManual=www.sefaz.al.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.al.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[AM]
NF-e=http://sistemas.sefaz.am.gov.br/nfeweb/formConsulta.do?tipoConsulta=Completa
CT-e=
NFC-e=http://sistemas.sefaz.am.gov.br/nfceweb/consultarNFCe.jsp
NFC-e(h)=http://sistemas.sefaz.am.gov.br/nfceweb-hom/consultarNFCe.jsp
NFC-e_ConsultaManual=www.sefaz.am.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.am.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[AP]
NF-e=http://www.sefaz.ap.gov.br/nfe.html
CT-e=
NFC-e=https://www.sefaz.ap.gov.br/nfce/nfcep.php
NFC-e(h)=https://www.sefaz.ap.gov.br/nfcehml/nfce.php
NFC-e_ConsultaManual=www.sefaz.ap.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.ap.gov.br/nfce/consulta
CTeQrCodeP=https://nfe.fazenda.sp.gov.br/CTeConsulta/qrCode
CTeQrCodeH=https://homologacao.nfe.fazenda.sp.gov.br/CTeConsulta/qrCode

[BA]
NF-e=http://nfe.sefaz.ba.gov.br/servicos/nfe/Modulos/Geral/NFENC_consulta_chave_acesso.aspx
CT-e=http://www.sefaz.rs.gov.br/CTE/CTE-COM.aspx
NFC-e=http://nfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx
NFC-e(h)=http://hnfe.sefaz.ba.gov.br/servicos/nfce/qrcode.aspx
NFC-e_ConsultaManual=www.sefaz.ba.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=http://hinternet.sefaz.ba.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[CE]
NF-e=http://nfe.sefaz.ce.gov.br/pages/consulta/welcome.jsf
CT-e=
NFC-e=http://nfce.sefaz.ce.gov.br/pages/ShowNFCe.html
NFC-e(h)=http://nfceh.sefaz.ce.gov.br/pages/ShowNFCe.html
NFC-e_ConsultaManual=www.sefaz.ce.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.ce.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[DF]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx
NFC-e(h)=http://dec.fazenda.df.gov.br/ConsultarNFCe.aspx
NFC-e_ConsultaManual=www.fazenda.df.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.fazenda.df.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[ES]
NF-e=http://internet.sefaz.es.gov.br/informacoes/nfe/consulta/consultanfe.php
CT-e=
NFC-e=http://app.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx
NFC-e(h)=http://homologacao.sefaz.es.gov.br/ConsultaNFCe/qrcode.aspx
NFC-e_ConsultaManual=www.sefaz.es.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.es.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[GO]
NF-e=http://www.projetos.goias.gov.br/nfe/index.php?idEditoria=3344
CT-e=
NFC-e=http://nfe.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe
NFC-e(h)=http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe
NFC-e_ConsultaManual=www.sefaz.go.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=http://homolog.sefaz.go.gov.br/nfeweb/sites/nfce/danfeNFCe
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[MA]
NF-e=http://nfeproducao.sefaz.ma.gov.br/gerenfe/
CT-e=
NFC-e=http://www.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp
NFC-e(h)=http://www.hom.nfce.sefaz.ma.gov.br/portal/consultarNFCe.jsp
NFC-e_ConsultaManual=www.sefaz.ma.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.ma.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[MG]
NF-e=http://nfe.fazenda.mg.gov.br/portalnfe/sistema/consultaarg.xhtml
CT-e=http://cte.fazenda.mg.gov.br/portalcte/sistema/consultaarg.xhtml
NFC-e=https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml
NFC-e(h)=https://nfce.fazenda.mg.gov.br/portalnfce/sistema/qrcode.xhtml
NFC-e_ConsultaManual=http://nfce.fazenda.mg.gov.br/portalnfce
NFC-e_ConsultaManual(h)=http://hnfce.fazenda.mg.gov.br/portalnfce
CTeQrCodeP=https://cte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml
CTeQrCodeH=https://cte.fazenda.mg.gov.br/portalcte/sistema/qrcode.xhtml

[MS]
NF-e=http://www.nfe.ms.gov.br/nfeconsultapublica/consultanfe
CT-e=http://producao.consultacte.ms.gov.br/
NFC-e=http://www.dfe.ms.gov.br/nfce/qrcode
NFC-e(h)=http://www.dfe.ms.gov.br/nfce/qrcode
NFC-e_ConsultaManual=http://www.dfe.ms.gov.br/nfce/
NFC-e_ConsultaManual(h)=http://www.dfe.ms.gov.br/nfce/
CTeQrCodeP=http://www.dfe.ms.gov.br/cte/qrcode
CTeQrCodeH=http://www.dfe.ms.gov.br/cte/qrcode

[MT]
NF-e=http://www.sefaz.mt.gov.br/nfe/portal/consultanfe?tpc=1
CT-e=http://www.sefaz.mt.gov.br/cteautz/portal/consultacompleta
NFC-e=http://www.sefaz.mt.gov.br/nfce/consultanfce
NFC-e(h)=http://homologacao.sefaz.mt.gov.br/nfce/consultanfce
NFC-e_ConsultaManual=http://www.sefaz.mt.gov.br/nfce/consultanfce
NFC-e_ConsultaManual(h)=http://homologacao.sefaz.mt.gov.br/nfce/consultanfce
CTeQrCodeP=https://www.sefaz.mt.gov.br/cte/qrcode
CTeQrCodeH=https://homologacao.sefaz.mt.gov.br/cte/qrcode

[PA]
NF-e=https://app.sefa.pa.gov.br/nfe-consulta-web/index
CT-e=http://cte.fazenda.mg.gov.br/consulta/pages/consultaCte/consulta.cte;jsessionid=55F4327B401844919320E7AAB36B28DE.cte
NFC-e=https://appnfc.sefa.pa.gov.br/portal/view/consultas/nfce/nfceForm.seam
NFC-e(h)=https://appnfc.sefa.pa.gov.br/portal-homologacao/view/consultas/nfce/nfceForm.seam
NFC-e_ConsultaManual=www.sefa.pa.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefa.pa.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[PB]
NF-e=https://saplic.receita.pb.gov.br/atf/seg/SEGf_AcessarFuncao.jsp?cdFuncao=FIS_1004
CT-e=
NFC-e=http://www.sefaz.pb.gov.br/nfce
NFC-e(h)=http://www.sefaz.pb.gov.br/nfcehom
NFC-e_ConsultaManual=www.sefaz.pb.gov.br/nfce
NFC-e_ConsultaManual(h)=http://www.sefaz.pb.gov.br/nfcehom
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[PE]
NF-e=http://nfe.sefaz.pe.gov.br/nfe-web/consNfe?tp=C
CT-e=
NFC-e=http://nfce.sefaz.pe.gov.br/nfce/consulta
NFC-e(h)=http://nfcehomolog.sefaz.pe.gov.br/nfce/consulta
NFC-e_ConsultaManual=nfce.sefaz.pe.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=nfce.sefaz.pe.gov.br/nfce/consulta
CTeQrCodeP=https://nfe.fazenda.sp.gov.br/CTeConsulta/qrCode
CTeQrCodeH=https://homologacao.nfe.fazenda.sp.gov.br/CTeConsulta/qrCode

[PI]
NF-e=http://www.sefaz.pi.gov.br/nfe/formularioDePesquisa_Completa.jsp
CT-e=
NFC-e=http://www.sefaz.pi.gov.br/nfce/qrcode
NFC-e(h)=http://www.sefaz.pi.gov.br/nfce/qrcode
NFC-e_ConsultaManual=www.sefaz.pi.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.pi.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[PR]
NF-e=http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=44
CT-e=http://www.sped.fazenda.pr.gov.br/modules/conteudo/conteudo.php?conteudo=6
NFC-e=http://www.fazenda.pr.gov.br/nfce/qrcode
NFC-e(h)=http://www.fazenda.pr.gov.br/nfce/qrcode
NFC-e_ConsultaManual=http://www.fazenda.pr.gov.br
NFC-e_ConsultaManual(h)=http://www.fazenda.pr.gov.br
CTeQrCodeP=http://www.fazenda.pr.gov.br/cte/qrcode
CTeQrCodeH=http://www.fazenda.pr.gov.br/cte/qrcode

[RJ]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode
NFC-e(h)=http://www4.fazenda.rj.gov.br/consultaNFCe/QRCode
NFC-e_ConsultaManual=www.fazenda.rj.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.fazenda.rj.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[RN]
NF-e=https://nfe.set.rn.gov.br/NFeProdWSsemhttps/set_NFe/web/frm_consulta.aspx
CT-e=
NFC-e=http://nfce.set.rn.gov.br/consultarNFCe.aspx
NFC-e(h)=http://hom.nfce.set.rn.gov.br/consultarNFCe.aspx
NFC-e_ConsultaManual=www.set.rn.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.set.rn.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[RO]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp
NFC-e(h)=http://www.nfce.sefin.ro.gov.br/consultanfce/consulta.jsp
NFC-e_ConsultaManual=www.sefin.ro.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefin.ro.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[RR]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=https://www.sefaz.rr.gov.br/nfce/servlet/qrcode
NFC-e(h)=http://200.174.88.103:8080/nfce/servlet/qrcode
NFC-e_ConsultaManual=www.sefaz.rr.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.rr.gov.br/nfce/consulta
CTeQrCodeP=https://nfe.fazenda.sp.gov.br/CTeConsulta/qrCode
CTeQrCodeH=https://homologacao.nfe.fazenda.sp.gov.br/CTeConsulta/qrCode

[RS]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=http://www.sefaz.rs.gov.br/CTE/CTE-COM.aspx
NFC-e=https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx
NFC-e(h)=https://www.sefaz.rs.gov.br/NFCE/NFCE-COM.aspx
NFC-e_ConsultaManual=www.sefaz.rs.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=www.sefaz.rs.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[SC]
NF-e=http://nfe.sef.sc.gov.br/index.php?option=com_wrapper&Itemid=50
CT-e=http://www.cte.sef.sc.gov.br/index.php?option=com_wrapper&Itemid=128
NFC-e=https://sat.sef.sc.gov.br/nfce/consulta
NFC-e(h)=https://hom.sat.sef.sc.gov.br/nfce/consulta
NFC-e_ConsultaManual=https://sat.sef.sc.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=https://hom.sat.sef.sc.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[SE]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://www.nfce.se.gov.br/nfce/qrcode
NFC-e(h)=http://www.hom.nfe.se.gov.br/nfce/qrcode
NFC-e_ConsultaManual=http://www.nfce.se.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=http://www.hom.nfe.se.gov.br/nfce/consulta
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[SP]
NF-e=https://nfe.fazenda.sp.gov.br/ConsultaNFe/consulta/publica/ConsultarNFe.aspx
CT-e=https://nfe.fazenda.sp.gov.br/CTECONSULTA/consulta/publica/ConsultarCTe.aspx
NFC-e=https://www.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx
NFC-e(h)=https://www.homologacao.nfce.fazenda.sp.gov.br/NFCeConsultaPublica/Paginas/ConsultaQRCode.aspx
NFC-e_ConsultaManual=https://www.nfce.fazenda.sp.gov.br/consulta
NFC-e_ConsultaManual(h)=https://www.homologacao.nfce.fazenda.sp.gov.br/consulta
CF-e=https://satsp.fazenda.sp.gov.br/COMSAT/Public/ConsultaPublica/ConsultaPublicaCfe.aspx
CTeQrCodeP=https://nfe.fazenda.sp.gov.br/CTeConsulta/qrCode
CTeQrCodeH=https://homologacao.nfe.fazenda.sp.gov.br/CTeConsulta/qrCode

[TO]
NF-e=http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx?chaveNFe=#chave_acesso#
CT-e=
NFC-e=http://apps.sefaz.to.gov.br/portal-nfce/qrcodeNFCe
NFC-e(h)=http://apps.sefaz.to.gov.br/portal-nfce-homologacao/qrcodeNFCe
NFC-e_ConsultaManual=www.sefaz.to.gov.br/nfce/consulta
NFC-e_ConsultaManual(h)=http://homologacao.sefaz.to.gov.br/nfce/consulta.jsf
CTeQrCodeP=https://dfe-portal.svrs.rs.gov.br/cte/qrCode
CTeQrCodeH=https://dfe-portal.svrs.rs.gov.br/cte/qrCode

[xml-ped-sit]
NF-e=<?xml version="1.0" encoding="utf-8"?><consSitNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><tpEmis>#tpemis#</tpEmis><chNFe>#chave_acesso#</chNFe></consSitNFe>
NFC-e=<?xml version="1.0" encoding="utf-8"?><consSitNFe xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><tpEmis>#tpemis#</tpEmis><chNFe>#chave_acesso#</chNFe></consSitNFe>
CT-e=<?xml version="1.0" encoding="utf-8"?><consSitCTe xmlns="http://www.portalfiscal.inf.br/cte" versao="4.00"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><tpEmis>#tpemis#</tpEmis><chCTe>#chave_acesso#</chCTe></consSitCTe>
MDF-e=<?xml version="1.0" encoding="utf-8"?><consSitMDFe xmlns="http://www.portalfiscal.inf.br/mdfe" versao="3.00"><tpAmb>1</tpAmb><xServ>CONSULTAR</xServ><tpEmis>#tpemis#</tpEmis><chMDFe>#chave_acesso#</chMDFe></consSitMDFe>
NFC-e_ConsultaManual=
NFC-e_ConsultaManual(h)=

[FIM]
Fim=1
