* ---------------------------------------------------------------------------------
* Assinar XML
* ---------------------------------------------------------------------------------
#IfNdef __XHARBOUR__
   #xcommand TRY => BEGIN SEQUENCE WITH {| oErr | Break( oErr ) }
   #xcommand CATCH [<!oErr!>] => RECOVER [USING <oErr>] <-oErr->
#endif

Function AssinarXML()
   Local oExceptionInterop, oErro, oAssinaturaDigital, oCertificadoDigital, base64
   Local xmlNFe, xmlAssinado, nHandle
   
   //Criar objeto para pegar exceção do CSHARP
   oExceptionInterop = CreateObject("Unimake.Exceptions.ThrowHelper")

   //Criar a string do XML
   xmlNFe := [<?xml version="1.0" encoding="utf-8"?>]
   xmlNFe += [<NFe xmlns="http://www.portalfiscal.inf.br/nfe">]
   xmlNFe +=    [<infNFe versao="4.00" Id="NFe41220806117473000150550010000580261977524394">]
   xmlNFe +=       [<ide>]
   xmlNFe +=          [<cUF>41</cUF>]
   xmlNFe +=          [<cNF>97752439</cNF>]
   xmlNFe +=          [<natOp>VENDA PRODUC.DO ESTABELEC</natOp>]
   xmlNFe +=          [<mod>55</mod>]
   xmlNFe +=          [<serie>1</serie>]
   xmlNFe +=          [<nNF>58026</nNF>]
   xmlNFe +=          [<dhEmi>2022-08-17T18:46:56-03:00</dhEmi>]
   xmlNFe +=          [<dhSaiEnt>2022-08-17T18:46:56-03:00</dhSaiEnt>]
   xmlNFe +=          [<tpNF>1</tpNF>]
   xmlNFe +=          [<idDest>2</idDest>]
   xmlNFe +=          [<cMunFG>4118402</cMunFG>]
   xmlNFe +=          [<tpImp>1</tpImp>]
   xmlNFe +=          [<tpEmis>1</tpEmis>]
   xmlNFe +=          [<cDV>4</cDV>]
   xmlNFe +=          [<tpAmb>2</tpAmb>]
   xmlNFe +=          [<finNFe>1</finNFe>]
   xmlNFe +=          [<indFinal>1</indFinal>]
   xmlNFe +=          [<indPres>1</indPres>]
   xmlNFe +=          [<procEmi>0</procEmi>]
   xmlNFe +=          [<verProc>TESTE 1.00</verProc>]
   xmlNFe +=          [<NFref>]
   xmlNFe +=             [<refNFe>00000000000000000000000chavenfedevolvida00000000000000</refNFe>]
   xmlNFe +=             [<refNF>]
   xmlNFe +=                [<cUF>41</cUF>]
   xmlNFe +=                [<AAMM>2212</AAMM>]
   xmlNFe +=                [<CNPJ>00000000000000</CNPJ>]
   xmlNFe +=                [<mod>01</mod>]
   xmlNFe +=                [<serie>1</serie>]
   xmlNFe +=                [<nNF>102</nNF>]
   xmlNFe +=             [</refNF>]
   xmlNFe +=          [</NFref>]
   xmlNFe +=       [</ide>]
   xmlNFe +=       [<emit>]
   xmlNFe +=          [<CNPJ>06117473000150</CNPJ>]
   xmlNFe +=          [<xNome>UNIMAKE SOLUCOES CORPORATIVAS LTDA</xNome>]
   xmlNFe +=          [<xFant>UNIMAKE - PARANAVAI</xFant>]
   xmlNFe +=          [<enderEmit>]
   xmlNFe +=             [<xLgr>RUA PAULO ANTONIO COSTA</xLgr>]
   xmlNFe +=             [<nro>575</nro>]
   xmlNFe +=             [<xBairro>CENTRO</xBairro>]
   xmlNFe +=             [<cMun>4118402</cMun>]
   xmlNFe +=             [<xMun>PARANAVAI</xMun>]
   xmlNFe +=             [<UF>PR</UF>]
   xmlNFe +=             [<CEP>87707210</CEP>]
   xmlNFe +=             [<cPais>1058</cPais>]
   xmlNFe +=             [<xPais>BRASIL</xPais>]
   xmlNFe +=             [<fone>04431421010</fone>]
   xmlNFe +=          [</enderEmit>]
   xmlNFe +=          [<IE>9032000301</IE>]
   xmlNFe +=          [<IM>14018</IM>]
   xmlNFe +=          [<CNAE>6202300</CNAE>]
   xmlNFe +=          [<CRT>1</CRT>]
   xmlNFe +=       [</emit>]
   xmlNFe +=       [<dest>]
   xmlNFe +=          [<CNPJ>04218457000128</CNPJ>]
   xmlNFe +=          [<xNome>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xNome>]
   xmlNFe +=          [<enderDest>]
   xmlNFe +=             [<xLgr>AVENIDA DA SAUDADE</xLgr>]
   xmlNFe +=             [<nro>1555</nro>]
   xmlNFe +=             [<xBairro>CAMPOS ELISEOS</xBairro>]
   xmlNFe +=             [<cMun>3543402</cMun>]
   xmlNFe +=             [<xMun>RIBEIRAO PRETO</xMun>]
   xmlNFe +=             [<UF>SP</UF>]
   xmlNFe +=             [<CEP>14080000</CEP>]
   xmlNFe +=             [<cPais>1058</cPais>]
   xmlNFe +=             [<xPais>BRASIL</xPais>]
   xmlNFe +=             [<fone>01639611500</fone>]
   xmlNFe +=          [</enderDest>]
   xmlNFe +=          [<indIEDest>1</indIEDest>]
   xmlNFe +=          [<IE>582614838110</IE>]
   xmlNFe +=          [<email>janelaorp@janelaorp.com.br</email>]
   xmlNFe +=       [</dest>]
   xmlNFe +=       [<det nItem="1">]
   xmlNFe +=          [<prod>]
   xmlNFe +=             [<cProd>00001</cProd>]
   xmlNFe +=             [<cEAN>SEM GTIN</cEAN>]
   xmlNFe +=             [<xProd>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>]
   xmlNFe +=             [<NCM>84714900</NCM>]
   xmlNFe +=             [<CFOP>6101</CFOP>]
   xmlNFe +=             [<uCom>LU</uCom>]
   xmlNFe +=             [<qCom>1</qCom>]
   xmlNFe +=             [<vUnCom>84.9</vUnCom>]
   xmlNFe +=             [<vProd>84.90</vProd>]
   xmlNFe +=             [<cEANTrib>SEM GTIN</cEANTrib>]
   xmlNFe +=             [<uTrib>LU</uTrib>]
   xmlNFe +=             [<qTrib>1</qTrib>]
   xmlNFe +=             [<vUnTrib>84.9</vUnTrib>]
   xmlNFe +=             [<indTot>1</indTot>]
   xmlNFe +=             [<xPed>300474</xPed>]
   xmlNFe +=             [<nItemPed>1</nItemPed>]
   xmlNFe +=          [</prod>]
   xmlNFe +=          [<imposto>]
   xmlNFe +=             [<vTotTrib>12.63</vTotTrib>]
   xmlNFe +=             [<ICMS>]
   xmlNFe +=                [<ICMSSN101>]
   xmlNFe +=                   [<orig>0</orig>]
   xmlNFe +=                   [<CSOSN>101</CSOSN>]
   xmlNFe +=                   [<pCredSN>2.8255</pCredSN>]
   xmlNFe +=                   [<vCredICMSSN>2.40</vCredICMSSN>]
   xmlNFe +=                [</ICMSSN101>]
   xmlNFe +=             [</ICMS>]
   xmlNFe +=             [<PIS>]
   xmlNFe +=                [<PISOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pPIS>0.0000</pPIS>]
   xmlNFe +=                   [<vPIS>0.00</vPIS>]
   xmlNFe +=                [</PISOutr>]
   xmlNFe +=             [</PIS>]
   xmlNFe +=             [<COFINS>]
   xmlNFe +=                [<COFINSOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pCOFINS>0.0000</pCOFINS>]
   xmlNFe +=                   [<vCOFINS>0.00</vCOFINS>]
   xmlNFe +=                [</COFINSOutr>]
   xmlNFe +=             [</COFINS>]
   xmlNFe +=          [</imposto>]
   xmlNFe +=       [</det>]
   xmlNFe +=       [<det nItem="2">]
   xmlNFe +=          [<prod>]
   xmlNFe +=             [<cProd>00002</cProd>]
   xmlNFe +=             [<cEAN>SEM GTIN</cEAN>]
   xmlNFe +=             [<xProd>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>]
   xmlNFe +=             [<NCM>84714900</NCM>]
   xmlNFe +=             [<CFOP>6101</CFOP>]
   xmlNFe +=             [<uCom>LU</uCom>]
   xmlNFe +=             [<qCom>1</qCom>]
   xmlNFe +=             [<vUnCom>84.9</vUnCom>]
   xmlNFe +=             [<vProd>84.90</vProd>]
   xmlNFe +=             [<cEANTrib>SEM GTIN</cEANTrib>]
   xmlNFe +=             [<uTrib>LU</uTrib>]
   xmlNFe +=             [<qTrib>1</qTrib>]
   xmlNFe +=             [<vUnTrib>84.9</vUnTrib>]
   xmlNFe +=             [<indTot>1</indTot>]
   xmlNFe +=             [<xPed>300474</xPed>]
   xmlNFe +=             [<nItemPed>1</nItemPed>]
   xmlNFe +=          [</prod>]
   xmlNFe +=          [<imposto>]
   xmlNFe +=             [<vTotTrib>12.63</vTotTrib>]
   xmlNFe +=             [<ICMS>]
   xmlNFe +=                [<ICMSSN101>]
   xmlNFe +=                   [<orig>0</orig>]
   xmlNFe +=                   [<CSOSN>101</CSOSN>]
   xmlNFe +=                   [<pCredSN>2.8255</pCredSN>]
   xmlNFe +=                   [<vCredICMSSN>2.40</vCredICMSSN>]
   xmlNFe +=                [</ICMSSN101>]
   xmlNFe +=             [</ICMS>]
   xmlNFe +=             [<PIS>]
   xmlNFe +=                [<PISOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pPIS>0.0000</pPIS>]
   xmlNFe +=                   [<vPIS>0.00</vPIS>]
   xmlNFe +=                [</PISOutr>]
   xmlNFe +=             [</PIS>]
   xmlNFe +=             [<COFINS>]
   xmlNFe +=                [<COFINSOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pCOFINS>0.0000</pCOFINS>]
   xmlNFe +=                   [<vCOFINS>0.00</vCOFINS>]
   xmlNFe +=                [</COFINSOutr>]
   xmlNFe +=             [</COFINS>]
   xmlNFe +=          [</imposto>]
   xmlNFe +=       [</det>]
   xmlNFe +=       [<det nItem="3">]
   xmlNFe +=          [<prod>]
   xmlNFe +=             [<cProd>00003</cProd>]
   xmlNFe +=             [<cEAN>SEM GTIN</cEAN>]
   xmlNFe +=             [<xProd>NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL</xProd>]
   xmlNFe +=             [<NCM>84714900</NCM>]
   xmlNFe +=             [<CFOP>6101</CFOP>]
   xmlNFe +=             [<uCom>LU</uCom>]
   xmlNFe +=             [<qCom>1</qCom>]
   xmlNFe +=             [<vUnCom>84.9</vUnCom>]
   xmlNFe +=             [<vProd>84.90</vProd>]
   xmlNFe +=             [<cEANTrib>SEM GTIN</cEANTrib>]
   xmlNFe +=             [<uTrib>LU</uTrib>]
   xmlNFe +=             [<qTrib>1</qTrib>]
   xmlNFe +=             [<vUnTrib>84.9</vUnTrib>]
   xmlNFe +=             [<indTot>1</indTot>]
   xmlNFe +=             [<xPed>300474</xPed>]
   xmlNFe +=             [<nItemPed>1</nItemPed>]
   xmlNFe +=          [</prod>]
   xmlNFe +=          [<imposto>]
   xmlNFe +=             [<vTotTrib>12.63</vTotTrib>]
   xmlNFe +=             [<ICMS>]
   xmlNFe +=                [<ICMSSN101>]
   xmlNFe +=                   [<orig>0</orig>]
   xmlNFe +=                   [<CSOSN>101</CSOSN>]
   xmlNFe +=                   [<pCredSN>2.8255</pCredSN>]
   xmlNFe +=                   [<vCredICMSSN>2.40</vCredICMSSN>]
   xmlNFe +=                [</ICMSSN101>]
   xmlNFe +=             [</ICMS>]
   xmlNFe +=             [<PIS>]
   xmlNFe +=                [<PISOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pPIS>0.0000</pPIS>]
   xmlNFe +=                   [<vPIS>0.00</vPIS>]
   xmlNFe +=                [</PISOutr>]
   xmlNFe +=             [</PIS>]
   xmlNFe +=             [<COFINS>]
   xmlNFe +=                [<COFINSOutr>]
   xmlNFe +=                   [<CST>99</CST>]
   xmlNFe +=                   [<vBC>0.00</vBC>]
   xmlNFe +=                   [<pCOFINS>0.0000</pCOFINS>]
   xmlNFe +=                   [<vCOFINS>0.00</vCOFINS>]
   xmlNFe +=                [</COFINSOutr>]
   xmlNFe +=             [</COFINS>]
   xmlNFe +=          [</imposto>]
   xmlNFe +=       [</det>]
   xmlNFe +=       [<total>]
   xmlNFe +=          [<ICMSTot>]
   xmlNFe +=             [<vBC>0.00</vBC>]
   xmlNFe +=             [<vICMS>0.00</vICMS>]
   xmlNFe +=             [<vICMSDeson>0.00</vICMSDeson>]
   xmlNFe +=             [<vFCP>0.00</vFCP>]
   xmlNFe +=             [<vBCST>0.00</vBCST>]
   xmlNFe +=             [<vST>0.00</vST>]
   xmlNFe +=             [<vFCPST>0.00</vFCPST>]
   xmlNFe +=             [<vFCPSTRet>0.00</vFCPSTRet>]
   xmlNFe +=             [<vProd>254.70</vProd>]
   xmlNFe +=             [<vFrete>0.00</vFrete>]
   xmlNFe +=             [<vSeg>0.00</vSeg>]
   xmlNFe +=             [<vDesc>0.00</vDesc>]
   xmlNFe +=             [<vII>0.00</vII>]
   xmlNFe +=             [<vIPI>0.00</vIPI>]
   xmlNFe +=             [<vIPIDevol>0.00</vIPIDevol>]
   xmlNFe +=             [<vPIS>0.00</vPIS>]
   xmlNFe +=             [<vCOFINS>0.00</vCOFINS>]
   xmlNFe +=             [<vOutro>0.00</vOutro>]
   xmlNFe +=             [<vNF>254.70</vNF>]
   xmlNFe +=             [<vTotTrib>37.89</vTotTrib>]
   xmlNFe +=          [</ICMSTot>]
   xmlNFe +=       [</total>]
   xmlNFe +=       [<transp>]
   xmlNFe +=          [<modFrete>0</modFrete>]
   xmlNFe +=          [<vol>]
   xmlNFe +=             [<qVol>1</qVol>]
   xmlNFe +=             [<esp>LU</esp>]
   xmlNFe +=             [<marca>UNIMAKE</marca>]
   xmlNFe +=          [</vol>]
   xmlNFe +=       [</transp>]
   xmlNFe +=       [<cobr>]
   xmlNFe +=          [<fat>]
   xmlNFe +=             [<nFat>057910</nFat>]
   xmlNFe +=             [<vOrig>254.70</vOrig>]
   xmlNFe +=             [<vDesc>0.00</vDesc>]
   xmlNFe +=             [<vLiq>254.70</vLiq>]
   xmlNFe +=          [</fat>]
   xmlNFe +=          [<dup>]
   xmlNFe +=             [<nDup>001</nDup>]
   xmlNFe +=             [<dVenc>2022-09-16</dVenc>]
   xmlNFe +=             [<vDup>127.35</vDup>]
   xmlNFe +=          [</dup>]
   xmlNFe +=          [<dup>]
   xmlNFe +=             [<nDup>002</nDup>]
   xmlNFe +=             [<dVenc>2022-10-16</dVenc>]
   xmlNFe +=             [<vDup>127.35</vDup>]
   xmlNFe +=          [</dup>]
   xmlNFe +=       [</cobr>]
   xmlNFe +=       [<pag>]
   xmlNFe +=          [<detPag>]
   xmlNFe +=             [<indPag>0</indPag>]
   xmlNFe +=             [<tPag>01</tPag>]
   xmlNFe +=             [<vPag>254.70</vPag>]
   xmlNFe +=          [</detPag>]
   xmlNFe +=       [</pag>]
   xmlNFe +=       [<infAdic>]
   xmlNFe +=          [<infCpl>;CONTROLE: 0000241197;PEDIDO(S) ATENDIDO(S): 300474;Empresa optante pelo simples nacional, conforme lei compl. 128 de 19/12/2008;Permite o aproveitamento do credito de ICMS no valor de R$ 2,40, correspondente ao percentual de 2,83% . Nos termos do Art. 23 - LC 123/2006 (Resolucoes CGSN n. 10/2007 e 53/2008);Voce pagou aproximadamente: R$ 6,69 trib. federais / R$ 5,94 trib. estaduais / R$ 0,00 trib. municipais. Fonte: IBPT/empresometro.com.br 18.2.B A3S28F;</infCpl>]
   xmlNFe +=       [</infAdic>]
   xmlNFe +=       [<infRespTec>]
   xmlNFe +=          [<CNPJ>06117473000150</CNPJ>]
   xmlNFe +=          [<xContato>Ze das Couves</xContato>]
   xmlNFe +=          [<email>zedascouves@gmail.com</email>]
   xmlNFe +=          [<fone>04430000000</fone>]
   xmlNFe +=       [</infRespTec>]
   xmlNFe +=    [</infNFe>]
   xmlNFe += [</NFe>]

   //Salvar o XML sem assinatura
   nHandle := fCreate("d:\testenfe\xmlNFeTeste.xml")
   FWrite(nHandle, xmlNFe)
   FClose(nHandle)

   Try
      //Assinar o XML passando o certificado no formato .PFX
      oAssinaturaDigital := CreateObject("Unimake.Business.DFe.Security.AssinaturaDigitalInterop")
      xmlAssinado := oAssinaturaDigital:Assinar(xmlNFe, "NFe", "infNFe", "d:\projetos\UnimakePV.pfx", "12345678", 0, .T., "Id", .T.)      

      //Salvar o XML assinado.
      nHandle := fCreate("d:\testenfe\xmlAssinadoTeste.xml")
      FWrite(nHandle, xmlAssinado)
      FClose(nHandle)
      
      //Assinar o XML passando o certificado no formato base64
      oCertificadoDigital := CreateObject("Unimake.Business.Security.CertificadoDigitalInterop")
      base64 := oCertificadoDigital:ToBase64("d:\projetos\UnimakePV.pfx")

      oAssinaturaDigital := CreateObject("Unimake.Business.DFe.Security.AssinaturaDigitalInterop")
      xmlAssinado := oAssinaturaDigital:Assinar(xmlNFe, "NFe", "infNFe", base64, "12345678", 0, .T., "Id", .T.)

      //Salvar o XML assinado.
      nHandle := fCreate("d:\testenfe\xmlAssinadoBase64Teste.xml")
      FWrite(nHandle, xmlAssinado)
      FClose(nHandle)

      ? "XML assinado com sucesso."
      ?
      ?

   Catch oErro
      //Demonstrar exceções geradas no proprio Harbour, se existir.
      ? "ERRO"
      ? "===="
      ? "Falha ao assinar o XML."
      ? oErro:Description
      ? oErro:Operation

      //Demonstrar a exceção do CSHARP
      ?
      ? "Excecao do CSHARP - Message: ", oExceptionInterop:GetMessage()
      ? "Excecao do CSHARP - Codigo: ", oExceptionInterop:GetErrorCode()
      ?
   End	  
   
   Wait
Return