Prezado(a) CLIENTE DESTINATARIO,
Segue em anexo, o arquivo eletrônico da sua Nota Fiscal devidamente autorizado,
além de um arquivo em formato .pdf para fácil visualização.

Chave nota fiscal para consulta : xxxx000124866
Autorização de uso : xxxx00096378627 Data : 09/11/2010 Hora : 16:53:11
Link para consulta : http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx

ATENÇÃO : Não responda a esta mensagem, pois se trata de um processo automático. Caso queira se comunicar com
nossa empresa, responda para contato@contato.com.br

Atenciosamente,

EMPRESA TESTE
Endereço : RUA BENTO GONCALVES, XXX
Cidade : NOVO HAMBURGO - BOA VISTA - RS
Cnpj : XX XXX XXX 0001-XX
Telefone: 51 555-5555

Leitor de Nfe e Cte : http://www.nfe.fazenda.gov.br/portal/visualizador.aspx
Leitor de arquivos pdf : http://www.foxitsoftware.com/pdf/reader/
*********************************************************************************************

4 - Enviando a notificação de cancelamento de uma NF-e por email :
Siga o tópico 3 deste mesmo help : a unica diferença, é com relação a mensagem que será enviada :

O email que será enviado tem os seguintes anexos :

1 - Contém o arquivo .xml da NF-e apenas para escrituração e conferência;
O corpo da mensagem será semelhante a :

*********************************************************************************************
Prezado(a) MEU CLIENTE TESTE

ATENÇÃO ::: CANCELAMENTO DE NOTA FISCAL ELETRÔNICA :

Seguem dados de Cancelamento de Nota Fiscal Eletrônica :

Chave de Acesso : XXXXXX04637205000133550010000137411000137411
Data Nota Fiscal : 20/12/2010

Protocolo de Cancelamento : 1431001139XXXXX
Data e Hora de Cancelamento : 21/12/2010 09:19:04

Link para consulta : http://www.sefaz.rs.gov.br/NFE/NFE-COM.aspx

Atenciosamente,

EMPRESA TESTE
Endereço : RUA BENTO GONCALVES, XXX
Cidade : NOVO HAMBURGO RS
Cnpj : XX XXX XXX 0001-XX
Telefone: 51 3555-5555

Leitor de Nfe e Cte : http://www.nfe.fazenda.gov.br/portal/visualizador.aspx
Leitor de arquivos pdf : http://www.foxitsoftware.com/pdf/reader/
*********************************************************************************************

ATENÇÃO : Da mesma forma que sua empresa é OBRIGADA a enviar o arquivo .xml da NF-e para os destinatários, deve comunica-los caso tenha cancelado a NF-e.

CAMPUS INFORMÁTICA LTDA
(51) 3582-0202 - campus@sinos.net