12AC	Acre
27AL	Alagoas
13AM	Amazonas
16AP	Amapá
29BA	Bahia
23CE	Ceará
53DF	Distrito Federal
32ES	Espírito Santo
52GO	Goiás
21MA	Maranhão
31MG	Minas Gerais
50MS	Mato Grosso do Sul
51MT	Mato Grosso
15PA	Pará
25PB	Paraíba
26PE	Pernambuco
22PI	Piauí
41PR	Paraná
33RJ	Rio de Janeiro
24RN	Rio Grande do Norte
11RO	Rondônia
14RR	Roraima
43RS	Rio Grande do Sul
42SC	Santa Catarina
28SE	Sergipe
35SP	São Paulo
17TO	Tocantins