* Seta Ambiente
SET DATE TO BRITISH 
SET DEFAULT TO FULLPATH(CURDIR())
SET PATH TO PROGS;MENU;FULLPATH(CURDIR())
        
* Configuraçõoes UI
ACTIVATE WINDOW SCREEN
_SCREEN.WINDOWSTATE = 2
PUSH MENU _MSYSMENU 
DO .\MENU\MENU.MPR
ON SHUTDOWN QUIT

READ EVENTS
RELEASE ALL	

