<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://www.antt.gov.br/ciot"
           targetNamespace="http://www.antt.gov.br/ciot"
           elementFormDefault="qualified">
  <xs:include schemaLocation="tiposBasicosCIOTEFrete_v1.00.xsd" />
  <xs:include schemaLocation="declaracaoOperacaoTransporteEFrete_v1.00.xsd" />
  <xs:include schemaLocation="consultarCIOTGeradoEFrete_v1.00.xsd" />
  <xs:include schemaLocation="cancelamentoOperacaoTransporteEFrete_v1.00.xsd" />
  <xs:include schemaLocation="encerramentoOperacaoTransporteEFrete_v1.00.xsd" />
  <xs:include schemaLocation="consultarSituacaoTransportadorEFrete_v1.00.xsd" />
  <xs:include schemaLocation="consultarFrotaTransportadorEFrete_v1.00.xsd" />
  <xs:include schemaLocation="gravarMotoristaEFrete_v1.00.xsd" />
  <xs:include schemaLocation="gravarProprietarioEFrete_v1.00.xsd" />
  <xs:include schemaLocation="gravarVeiculoEFrete_v1.00.xsd" />
</xs:schema>
