using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Unimake.Business.DFe.Xml.NFe.Txt
{
    internal enum TpcnResources
    {
        AAMM,
        ano,
        anoFab,
        anoMod,
        adRemCBS,
        adRemIBS,
        adRemCBSReten,
        adRemCBSRet,
        adRemIBSRet,
        adRemIBSReten,
        adRemICMS,
        adRemICMSReten,
        adRemICMSRet,
        adRemIS,
        agropecuario,
        gAjusteCompet,
        gEstornoCred,
        vIBSEstCred,
        vCBSEstCred,
        gCredPresOper,
        gIBSCredPres,
        gCBSCredPres,
        vBCCredPres,
        cCredPres,
        pCredPres,
        vCredPres,
        vCredPresCondSus,
        balsa,

        cAerDes,
        cAerEmb,
        cAgreg,
        cAut,
        cap,
        capKG,
        capM3,
        cBenef,
        cClassTrib,
        indDoacao,
        cClassTribIS,
        cClassTribReg,
        cCor,
        cCorDENATRAN,
        cCT,
        cDC,
        cDV,
        cEAN,
        cBarra,
        cEANTrib,
        cBarraTrib,
        cEmbar,
        cEmbComb,
        cEnq,
        CEP,
        CEST,
        cExportador,
        cFabricante,
        CFOP,
        chassi,
        chave,
        chaveAcesso,
        chCTe,
        chCte,
        chMDFe,
        chNFe,
        chNF3e,
        chNFCom,
        chNFGas,
        chBPe,
        chCIOT,
        cilin,
        cIMP,
        cInt,
        CIOT,
        clEnq,
        cInfManu,
        CL,
        cListServ,
        cMDF,
        cMod,
        CMT,
        cMun,
        cMunFG,
        cMunFGIBS,
        cMunEnv,
        cMunIni,
        cMunFim,
        CNAE,
        cNF,
        CNPJ,
        CNPJ_CPF,
        CNPJAgeNav,
        CNPJDest,
        CNPJFab,
        CNPJForn,
        CNPJIF,
        CNPJPg,
        CNPJProd,
        CODIF,
        cOrgao,
        cOrgaoAutor,
        condVeic,
        COTM,
        cMunDescarga,
        cMunCarrega,
        cPais,
        CPF,
        CPFDest,
        CPFRespTec,
        cProd,
        cProdANP,
        cProdANVISA,
        cPrtDest,
        cPrtEmb,
        cRegTrib,
        CRT,
        cSelo,
        cServico,
        cSit,
        cSitTrib,
        CSOSN,
        CST,
        CSTIS,
        CSTReg,
        cStat,
        cTar,
        cTermCarreg,
        cTermDescarreg,
        cUF,
        cUFAutor,
        cUnid,
        cUFOrig,
        cBenefRBC,
        CNPJPag,
        CNPJReceb,

        dBaixa,
        dCompet,
        dDesemb,
        dDI,
        dEmi,
        defensivo,
        descr,
        descANP,
        descEvento,
        descOutros,
        destCalc,
        detEvento,
        detPag,
        dFab,
        DFeReferenciado,
        dFim,
        dhCons,
        dhCont,
        dhEmi,
        dhEvento,
        dhRecbto,
        dhRegEvento,
        dhResp,
        dhSaiEnt,
        dhTrem,
        dIni,
        dia,
        digVal,
        dIniAtiv,
        direc,
        dist,
        dPag,
        dPrev,
        dPrevAereo,
        dProg,
        dSaiEnt,
        dUltSit,
        dVal,
        dVenc,
        dVoo,

        email,
        emailDest,
        esp,
        espVeic,
        EXTIPI,

        ferrEmi,

        finNFe,
        fluxo,
        fone,
        forPag,

        gCBS,
        gCompraGov,
        gCredPresIBSZFM,
        gDevTrib,
        gDif,
        grEmb,
        gIBSCBS,
        gIBS,
        gIBSUF,
        gIBSCBSMono,
        gIBSMun,
        gMono,
        gMonoPadrao,
        gMonoReten,
        gMonoRet,
        gMonoDif,
        gPagAntecipado,
        gRed,
        gTransfCred,
        gTribCompraGov,
        gTribRegular,
        guiaTransito,

        hFim,
        hIni,
        hProg,

        hSaiEnt,
        dPrevEntrega,
        IBSCBS,
        IBSCBSTot,
        ICMS,
        ICMSUFDest,
        ID,
        Id,
        idDest,
        idEstrangeiro,
        idLote,
        indBemMovelUsado,
        indEscala,
        indSinc,
        idPedido,
        idPedidoCancelado,
        IdT,
        idTrem,
        idUnidCarga,
        idUnidTransp,
        IE,
        IEAtual,
        IEUnica,
        IEST,
        IM,
        indCredCTe,
        indCredNFe,
        indEmi,
        indFinal,
        indIEDest,
        indIncentivo,
        indISS,
        indISSRet,
        indNegociavel,
        indNFe,
        indPag,
        indPres,
        indIntermed,
        indProc,
        indSN,
        indTot,
        idCadIntTran,
        infAdFisco,
        infAdProd,
        infCpl,
        irin,
        IS,
        ISTot,
        ISUF,
        ISUFEmit,
        itemPedido,
        indImport,
        indDeduzDeson,
        idTermPag,

        justStatus,
        justStaOutra,

        lota,
        marca,
        matr,
        mod,
        modal,
        modBC,
        modBCST,
        motDesICMS,
        motRedAdRem,
        modFrete,
        nAdicao,
        nApol,
        nac,
        natOp,
        nAver,
        nBico,
        nBomba,
        nBooking,
        nCano,
        NCM,
        nCOO,
        nCompra,
        nCont,
        nCT,
        nDC,
        nCtrl,
        nDAR,
        nMDF,
        nDI,
        nDoc,
        nDup,
        nDraw,
        nECF,
        nFat,
        nFCI,
        nCFOP,
        NFref,
        nGuia,
        NItem,
        nItem,
        nItemPed,
        nLacre,
        nLote,
        nMinu,
        nMotor,
        nNF,
        nNFFin,
        nNFIni,
        nOCA,
        nOcc,
        nONU,
        nPed,
        nPeso,
        nProc,
        nProcSuframa,
        nProcesso,
        nProt,
        nProtEvento,
        nro,
        nRE,
        nRECOPI,
        nRec,
        nReceituario,
        nRoma,
        nSeq,
        nSeqAdic,
        nSeqEvento,
        nSerie,
        nTanque,
        numItem,
        nVag,
        nViag,
        nVol,
        nVoo,
        NSU,
        NVE,

        orig,
        origCalc,

        pAliqCBS,
        pAliqEfet,
        pAliqEfetRegIBSUF,
        pAliqEfetRegIBSMun,
        pAliqEfetRegCBS,
        pAliqIBSMun,
        pAliqIBSUF,
        pBCOp,
        pDif,
        pDifCBS,
        pDifIBS,
        pDevTrib,
        pDevol,
        pMixGN,
        pCBS,
        pCOFINS,
        pCredSN,
        pesoB,
        pesoBC,
        pesoL,
        pesoR,
        pFCP,
        pFCPST,
        pFCPSTRet,
        pFCPUFDest,
        pGLP,
        pGNn,
        pGNi,
        pIBSUF,
        pIBSMun,
        pICMS,
        pICMSRet,
        pICMSST,
        pICMSUFDest,
        pICMSInter,
        pICMSInterPart,
        pICMSOutraUF,
        pICMSSTRet,
        pICMSEfet,
        PIN,
        pIPI,
        pIS,
        PISOutr,
        placa,
        pMVAST,
        pontoFulgor,
        pot,
        pPIS,
        procEmi,
        proPred,
        pRedAliq,
        pRedBC,
        pRedBCST,
        pRedBCEfet,
        pRedBCOutraUF,
        prtDest,
        prtEmb,
        prtTrans,
        pST,
        pOrig,
        pRedAdRem,

        qBCProd,
        qCarga,
        qCom,
        qCT,
        qCTe,
        qExport,
        qLote,
        qMDFe,
        qNF,
        qNFe,
        qSelo,
        qtde,
        qtdeItem,
        qtdRat,
        qTemp,
        qTotAnt,
        qTotGer,
        qTotMes,
        qTotProd,
        qTrib,
        qUnid,
        qVag,
        qVol,
        qVolTipo,
        
        pBio,
        pRedutor,

        Ref,
        refCTe,
        refDFe,
        refDFeAnt,
        refCte,
        refCteAnu,
        refCTE,
        refNFe,
        RENAVAM,
        repEmi,
        respCancPedido,
        respPedido,
        respFat,
        respSeg,
        retira,
        RNTC,
        RNTRC,

        safra,
        SegCodBarra,
        serie,
        serieGuia,
        statCancPedido,
        statPedido,
        statPrazo,
        subser,
        subserie,

        tara,
        tBand,
        tMed,
        toma,
        tpAmb,
        tpALCZFMCBS,
        tpArma,
        tpAto,
        tpAutor,
        tpCar,
        tpComb,
        tpCredPresIBSZFM,
        competApur,
        tpCTe,
        tpDoc,
        tpEmb,
        tpEmis,
        tpEmit,
        tpEnteGov,
        tpEvento,
        tpGuia,
        tpHor,
        tpImp,
        tpIntegra,
        tpIntermedio,
        tpMed,
        tpNF,
        tpNav,
        tpNFDebito,
        tpNFCredito,
        tpOp,
        tpOperGov,
        tPag,
        xPag,
        tpPer,
        tpPint,
        tpProp,
        tpRest,
        tpRod,
        tpServ,
        tpTraf,
        tpUnidCarga,
        tpUnidTransp,
        tpVag,
        tpVeic,
        tpViaTransp,
        TU,

        UFEnv,
        UFGuia,
        UFFim,
        UFIni,
        UFPer,
        UFSaidaPais,
        UFTerceiro,
        uCom,
        UF,
        UFCons,
        UFDesemb,
        UFEmbarq,
        UFST,
        ultNSU,
        unidRat,
        uTrib,
        UFPag,
        UFReceb,

        vAFRMM,
        valor,
        vCarga,
        vCBS,
        vCBSMonoDif,
        vCBSMonoRet,
        vCBSMonoReten,
        vCredPresIBSZFM,
        vCSLL,
        vDescCond,
        vDescIncond,
        vDeducao,
        vDevTrib,
        vDif,
        vDocFisc,
        vFCP,
        pFCPDif,
        vFCPDif,
        vFCPEfet,
        vICMSDif,
        vICMSOp,
        vINSS,
        vIPIDevol,
        vIR,
        xLocDespacho,
        xLocExporta,
        vagao,
        vAliq,
        vAliqProd,
        vBC,
        vBCEfet,
        vBCIBSCBS,
        vBCICMS,
        vBCICMSST,
        vBCICMSSTCons,
        vBCICMSSTDest,
        vBCIRRF,
        vBCIS,
        vBCFCP,
        vBCFCPST,
        vBCOp,
        vBCRet,
        vBCRetPrev,
        vBCUFDest,
        vBCFCPUFDest,
        vBCST,
        vBCSTDest,
        vBCSTRet,
        vBCFCPSTRet,
        vBCOutraUF,
        vCBSMono,
        vFCPST,
        vICMSSTDeson,
        motDesICMSST,
        vCIDE,
        vCOFINS,
        indSomaCOFINSST,
        vComp,
        vCred,
        vCredICMSSN,
        vDAR,
        vDed,
        vDesc,
        vDescDI,
        vDespAdu,
        vDup,
        verAplic,
        verEvento,
        verProc,
        versao,
        versaoDados,
        versaoModal,
        vEncIni,
        vEncFin,
        vFCPSTRet,
        vFCPUFDest,
        vFor,
        vFrete,
        vIBS,
        vIBSUF,
        vIBSMono,
        vIBSMonoDif,
        vIBSMonoRet,
        vIBSMonoReten,
        vIBSMun,
        vICMS,
        vICMSDeson,
        vICMSRet,
        vICMSST,
        vICMSSTCons,
        vICMSSTDest,
        vICMSSTRet,
        vICMSOutraUF,
        vICMSUFDest,
        vICMSUFRemet,
        vICMSEfet,
        vICMSSubstituto,
        vII,
        VIN,
        vIOF,
        vIPI,
        vIRRF,
        vIS,
        vISS,
        vISSQN,
        vISSRet,
        vItem,
        vLiq,
        vLiqFor,
        vNF,
        vNFTot,
        vOrig,
        vOutro,
        vPag,
        vPart,
        vPIS,
        indSomaPISST,
        vPMC,
        vPrest,
        vProd,
        vRec,
        vRetCOFINS,
        vRetCSLL,
        vRetPIS,
        vRetPrev,
        vSeg,
        vServ,
        vST,
        vTar,
        vTotCBSMonoItem,
        vTotIBSMonoItem,
        vTroco,
        vTribCBS,
        vTribIBSMun,
        vTribIBSUF,
        vTribRegIBSUF,
        vTribRegIBSMun,
        vTribRegCBS,
        vTotDed,
        vTotTrib,
        vTPrest,
        vUnCom,
        vUnid,
        vUnit,
        vUnTrib,
        vValePed,
        qBCMono,
        vICMSMono,
        qBCMonoReten,
        vICMSMonoReten,
        qBCMonoRet,
        vICMSMonoRet,
        vICMSMonoOp,
        vICMSMonoDif,

        xAgente,
        xBairro,
        xBalsa,
        xCampo,
        xCaracAd,
        xCaracSer,
        xClaRisco,
        xCondUso,
        xCont,
        xCor,
        xCorrecao,
        xCpl,
        xDed,
        xDest,
        xDetRetira,
        xDime,
        xEmi,
        xEnder,
        xEvento,
        xFant,
        xJust,
        xLAgEmi,
        xLgr,
        xLocDesemb,
        xLocEmbarq,
        xMotivo,
        xmlns,
        xMun,
        xMunCarrega,
        xMunDescarga,
        xMunEnv,
        xMunFim,
        xMunIni,
        xNavio,
        xNEmp,
        xNome,
        xNomeAE,
        xObs,
        xOrgao,
        xOri,
        xOrig,
        xOutCat,
        xPais,
        xPass,
        xPed,
        xPref,
        xProd,
        xRegApur,
        xRota,
        xSeg,
        xServ,
        xTexto,
        dEmissao,
        infProt,
        protLivroCombustivel,
        chNFeRef,
        cCredPresumido,
        pCredPresumido,
        vCredPresumido
    }

    internal class NFeStrConstants
    {
        public static string NAME_SPACE_MDFE = "http://www.portalfiscal.inf.br/mdfe";
        public static string NAME_SPACE_CTE = "http://www.portalfiscal.inf.br/cte";
        public static string NAME_SPACE_NFE = "http://www.portalfiscal.inf.br/nfe";
        public static string NAME_SPACE_NF3E = "http://www.portalfiscal.inf.br/nf3e";
        public static string NAME_SPACE_NFCOM = "http://www.portalfiscal.inf.br/nfcom";
        public static string NAME_SPACE_NFGAS = "http://www.portalfiscal.inf.br/nfgas";
        public static string NAME_SPACE_BPE = "http://www.portalfiscal.inf.br/bpe";
        public static string NAME_SPACE_CIOT = "http://www.antt.gov.br/ciot";
        public static string NAME_SPACE_DCE = "http://www.portalfiscal.inf.br/dce";

        public static string proxyError = "Especifique o nome do servidor/usuário/senha e porta para conectar do servidor proxy";
        public static string versaoError = "Defina a versão";
        public static string Nome = "Nome";
        public static string Padrao = "Padrao";
        public static string Estado = "Estado";
        public static string Registro = "Registro";
        public static string Servico = "Servico";
        public static string SVC = "SVC";
        public static string LocalHomologacao = "LocalHomologacao";
        public static string LocalProducao = "LocalProducao";

        public static string nfe_configuracoes = "nfe_configuracoes";
        public static string PastaXmlAssinado = "PastaXmlAssinado";
        public static string PastaXmlEnvio = "PastaXmlEnvio";
        public static string PastaXmlEmLote = "PastaXmlEmLote";
        public static string PastaXmlRetorno = "PastaXmlRetorno";
        public static string PastaXmlEnviado = "PastaXmlEnviado";
        public static string PastaXmlErro = "PastaXmlErro";
        public static string PastaBackup = "PastaBackup";
        public static string PastaValidar = "PastaValidar";
        public static string PastaDownloadNFeDest = "PastaDownloadNFeDest";
        public static string ConfiguracaoDanfe = "ConfiguracaoDanfe";
        public static string ConfiguracaoCCe = "ConfiguracaoCCe";
        public static string PastaExeUniDanfe = "PastaExeUniDanfe";
        public static string PastaConfigUniDanfe = "PastaConfigUniDanfe";
        public static string PastaDanfeMon = "PastaDanfeMon";
        public static string XMLDanfeMonNFe = "XMLDanfeMonNFe";
        public static string XMLDanfeMonProcNFe = "XMLDanfeMonProcNFe";
        public static string XMLDanfeMonDenegadaNFe = "XMLDanfeMonDenegadaNFe";

        public static string UsuarioWS = "UsuarioWS";
        public static string SenhaWS = "SenhaWS";

        public static string FTPAtivo = "FTPAtivo";
        public static string FTPGravaXMLPastaUnica = "FTPGravaXMLPastaUnica";
        public static string FTPSenha = "FTPSenha";
        public static string FTPPastaAutorizados = "FTPPastaAutorizados";
        public static string FTPPastaRetornos = "FTPPastaRetornos";
        public static string FTPNomeDoUsuario = "FTPNomeDoUsuario";
        public static string FTPNomeDoServidor = "FTPNomeDoServidor";
        public static string FTPPorta = "FTPPorta";

        public static string CertificadoDigital = "CertificadoDigital";
        public static string CertificadoDigitalThumbPrint = "CertificadoDigitalThumbPrint";
        public static string CertificadoInstalado = "CertificadoInstalado";
        public static string CertificadoArquivo = "CertificadoArquivo";
        public static string CertificadoSenha = "CertificadoSenha";
        public static string CertificadoPIN = "CertificadoPIN";
        public static string ProviderCertificado = "ProviderCertificado";
        public static string ProviderTypeCertificado = "ProviderTypeCertificado";

        public static string AmbienteCodigo = "AmbienteCodigo";
        public static string DiasLimpeza = "DiasLimpeza";
        public static string DiretorioSalvarComo = "DiretorioSalvarComo";
        public static string GravarRetornoTXTNFe = "GravarRetornoTXTNFe";
        public static string GravarEventosNaPastaEnviadosNFe = "GravarEventosNaPastaEnviadosNFe";
        public static string GravarEventosCancelamentoNaPastaEnviadosNFe = "GravarEventosCancelamentoNaPastaEnviadosNFe";
        public static string GravarEventosDeTerceiros = "GravarEventosDeTerceiros";
        public static string CompactarNfe = "CompactarNfe";
        public static string TempoConsulta = "TempoConsulta";
        public static string UnidadeFederativaCodigo = "UnidadeFederativaCodigo";
        public static string IndSinc = "IndSinc";
    }
}
